### ISSUE TITLE
Black produced different code on the second pass of the formatter

### ISSUE THREAD

**Issue by milicag** [LBNL-ETA/MSWH#27]
Black Python formatter throws the following:
```
(mswh) mgrahovac@milicag mswh % black . --line-length 79
reformatted /Users/mgrahovac/repos/MSWH/mswh/tools/unit_converters.py
error: cannot format /Users/mgrahovac/repos/MSWH/mswh/system/models.py: INTERNAL ERROR: Black produced different code on the second pass of the formatter.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: /var/folders/pm/5jhq3l915dl6sb34wznrz0440000gp/T/blk_qj28zjr0.log
```

**Comment by rhosbach** [comment]
@milicag, thanks for bringing this to my attention.  I think it's worth mentioning here a couple of things:

1. The code should still work just fine (_i.e._, Black won't have broke anything).
2. Black is meant to be deterministic, which is why this error is being thrown.  In this sense, this error is actually a good thing, because Black is recognizing that doing a subsequent formatting of the code is providing a different format than the first time Black formatted the code. 

If it were me, I would just leave it as is.

**Comment by milicag** [comment]
@rhosbach Thanks!

**Comment by milicag** [comment]
I'm now inclined to look at the log and potentially address it in one of the further JOSS review PRs I create (hoping that it is a minor issue). It certainly does not matter at all for the functionality of the code.

**Comment by rhosbach** [comment]
Exactly.  And, as I said, at least from a cursory glance I don't see any crazy formatting issues.

**Comment by milicag** [comment]
Thanks Rob!
